### PR TITLE
Add masterclass signup section

### PR DESCRIPTION
**Pull request by khalilcodes**
Tasks from #84 

### Summary

This PR replaces the hero with signup to masterclass on the homepage.

### Changes

* remove old hero
* Add signup to masterclass section in `pages/index.js`

### Preview

localhost_3000_ (1)

### CODE REVIEW

**Comment by rufuspollock** [comment]
@khalilcodes great - we can just remove old hero ...

**Comment by khalilcodes** [comment]
@rufuspollock removed hero

**Comment by rufuspollock** [comment]
@khalilcodes have we fixed signup form?

**Comment by khalilcodes** [comment]
@rufuspollock have some notes here on form https://github.com/life-itself/diginomics/issues/77#issuecomment-1535639215, suggest we merge this and implement it with a submit confirmation page ?

**Comment by rufuspollock** [comment]
@khalilcodes merged and let's do redirect asap 😄

**Pull request merged**
